### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by Arvamer** [Kadek/PIO-roguelike#2]
W tym tygodniu labki z PIO (cokolwiek ten skrót ma oznaczać) oraz oba kolokwia za nami, więc przydało by się w końcu coś konkretnego zrobić. Pod spodem lista co wg. mnie należy teraz zaimplementować, dalej bardziej szczegółowe informacje dotyczące poszczególnych zadań. Napiszcie za co chcecie się zabrać, ja mogę wziąć to co zostanie (w sensie jedną rzecz a nie wszystkie :) ).

- [x] Actor
- [X] Input System (Arvamer)
- [x] Wczytywanie informacji o znakach w teksturze (zobacz [tutaj](https://github.com/Kadek/PIO-roguelike/blob/master/core/src/com/pio/roguelike/map/ASCIITextureInfo.java#L8-17))
- [x] Klasa Item (rafalx200)
- [x] ItemContainer (mgierlach)

Do implementacji większości elementów przyda się nasz wspaniały [diagram klas](http://creately.com/diagram/in0fddm0/F84MpYGXnYHicytV45oucaLpo%3D) oraz [dokumentacja libgdx](https://github.com/libgdx/libgdx/wiki).

Taka jeszcze jedna uwaga - w diagramie klas używałem vec2 do określenia uporządkowanej pary (float, float). **Nie implementujemy tego w Javie.** Klasy w Javie mogą być alokowane tylko na stercie oraz nie ma przeciążenia operatorów (ale przeciążenia nazw funkcji już są…) - taki wektor byłby nieefektywny i mało wnosił do wygody programowania. Wszędzie tam gdzie jest na diagramie  vec2 używamy 2 zmiennych typu float.

## Actor
Na razie zakładamy że jest to tylko gracz. Powinien się móc przemieszczać, oraz oczywiście wyświetlać na mapie (w końcu dziedziczy po Sprite z libgdx). Do implementacji wymagane jest zdefiniowane InputAction (robi to osoba odpowiedzialna za InputSystem)

## Input System
Przede wszystkim definiuje InputAction (enum, czy cokolwiek tam się używa w Javie). Trudniejszą rzeczą jest pętla główna naszej gry (szczególnie z podejściem OOOP libgdx i jego ApplicationAdapter…). Idea jest taka, że logika gry jest uruchamiana w stałych odstępach czasowych, a renderowanie jak szybko się da. Jest o tym sporo artykułów, np. [tutaj](http://gameprogrammingpatterns.com/game-loop.html) lub [tutaj](http://gafferongames.com/game-physics/fix-your-timestep/), trzeba się z jakimś zapoznać. W części logicznej na razie informujemy aktora (gracza) co realny gracz wykonał (metoda handle_input) - czyli np. jak nacisnął na klawiaturze "W" to wywołujemy handle_input(InputAction::MoveUp).

## Klasa Item
To co na diagramie :). Dobrze by było wczytywać informacje o przedmiotach z pliku. Ja proponuję do tego użyć yaml, jako że jest czytelny. Przykładowy plik mógłby wyglądać tak:
```yaml
name: Excalibur
price: 9999
kind: sword
dmg_min: 23
dmg_max: 36
speed: 1.5
```
Na pewno znajdzie się jakaś biblioteka do parsowania plików yaml.

## ItemContainer
Tu informacje na diagramie klas są raczej bardzo poglądowe i nie należy się nimi za bardzo sugerować :). Na razie wystarczy nam jak będzie potrafiło wyświetlić listę przedmiotów, jako że daje to jakieś widoczne efekty. Później (czyli nie koniecznie na Sprint 2) trzeba będzie zaimplementować przenoszenie przedmiotów pomiędzy różnymi kontenerami (np. trup i gracz, albo gracz i /dev/null) i pewnie coś jeszcze co wyjdzie. Warto też pamiętać, że będzie dość dużo różnych obiektów które powinny się zachowywać jak ItemContainer - gracz, skrzynka, trup, pole na mapie itd. Dlatego powinno być to tak zaimplementowane, aby za dużo się nie napisać. Nie wiem na ile pozwalają interfejsy w Javie, ale podstawowym wymaganiem jest, żeby implementacja dla nowych obiektów był minimalna.

To chyba wszystko, piszcie poniżej co chcecie zrobić, albo jakie uwagi lub pytania macie, forkujcie repo i do roboty! Jeśli się ogarniemy to nie powinno nam to zając dużo czasu.

**Comment by rafalx200** [comment]
Nikt nic jeszcze nie napisał, więc ja zarezerwuje sobie Klasę Item.

**Comment by mgierlach** [comment]
w takim razie wezmę ItemContainer

**Comment by Arvamer** [comment]
W takim razie to ja biorę się z Input System

**Comment by Danalscy** [comment]
no to ja char metrykę :)

**Comment by Arvamer** [comment]
Jakby ktoś chciał przejrzeć przed scaleniem: #3

**Comment by xfix** [comment]
Jestem ostatni, więc rezerwuję Actor.

**Comment by xfix** [comment]
> Nie implementujemy tego w Javie. Klasy w Javie mogą być alokowane tylko na stercie

Bzdura. W teorii, `new` alokuje na stercie, ale [w praktyce tego nie robi jeśli JVM jest w stanie udowodnić że obiekt nie ucieknie](https://docs.oracle.com/javase/7/docs/technotes/guides/vm/performance-enhancements-7.html#escapeAnalysis).

JVM nie jest głupi. Dzisiejsze kompilatory są wystarczająco inteligentne by zmienić kod na bardziej wydajniejszy kiedy to możliwe. Zwłaszcza, nie ma sensu porównywanie wydajności kilku linijek kodu.
